# Generated by Django 5.0.14 on 2026-08-18 17:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_messageread_messageread_unique_message_user_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="chat/",
            ),
        ),
    ]
