# Generated by Django 5.0.14 on 2026-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0004_attachment_upload_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_cleared",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
