# Generated by Django 5.0.14 on 2026-09-01 16:22

import apps.messages.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_add_is_cleared_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.messages.storage.ChatAttachmentCloudinaryStorage(), upload_to='chat/'),
        ),
    ]
